name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: vonhautten

          # === GENERAL ===
          template: repository
          config_timezone: Asia/Jakarta
          config_display: columns

          # === BASE SECTIONS ===
          base: header, repositories

          # === STATS (LEFT PANEL) ===
          repositories_affiliations: owner
          repositories_skipped: ""
          repositories_forks: no

          # === LANGUAGES (RIGHT PANEL) ===
          languages: yes
          languages_analysis_timeout: 15
          languages_limit: 12
          languages_threshold: 0%
          languages_colors: github
          languages_details: bytes-size, percentage
          languages_sections: most-used
          languages_indepth: yes

          # === VISUAL ===
          config_order: base.header, base.repositories, languages
          config_padding: 8, 16
          config_layout: wide

          # === OUTPUT ===
          output_action: commit
          output_path: .
          filename: metrics.svg
