name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: vonhautten

          # === GENERAL ===
          template: repository
          config_timezone: Asia/Jakarta
          config_display: columns
          config_padding: 8, 16

          # === BASE SECTIONS ===
          base: header, repositories
          repositories_affiliations: owner
          repositories_forks: no
          repositories_skipped: ""

          # === LANGUAGES PLUGIN ===
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_threshold: 0%
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15

          # === ORDER ===
          config_order: base.header, base.repositories, plugin_languages

          # === OUTPUT ===
          output_action: commit
          filename: metrics.svg
